/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDriveFilesRouteImport } from './routes/api/drive-files'
import { Route as ApiResearchRouteImport } from './routes/api/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFilesRoute = ApiDriveFilesRouteImport.update({
  id: '/api/drive-files',
  path: '/api/drive-files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drive-files': typeof ApiDriveFilesRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drive-files': typeof ApiDriveFilesRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drive-files': typeof ApiDriveFilesRoute
  '/api/research': typeof ApiResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn' | '/api/chat' | '/api/drive-files' | '/api/research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/api/chat' | '/api/drive-files' | '/api/research'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/api/chat'
    | '/api/drive-files'
    | '/api/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDriveFilesRoute: typeof ApiDriveFilesRoute
  ApiResearchRoute: typeof ApiResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-files': {
      id: '/api/drive-files'
      path: '/api/drive-files'
      fullPath: '/api/drive-files'
      preLoaderRoute: typeof ApiDriveFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDriveFilesRoute: ApiDriveFilesRoute,
  ApiResearchRoute: ApiResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
