"""Google Analytics 4 Data API client with OAuth 2.0 authentication."""

import json
import logging
import os
import re
import tempfile
import time
from pathlib import Path
from typing import Any

import pandas as pd
import requests
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
)
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow

# OAuth scopes — minimal blast radius: read-only Analytics + Drive file picker
# (readonly) + write-back to app-created files only (drive.file).
SCOPES = [
    "https://www.googleapis.com/auth/analytics.readonly",
    "https://www.googleapis.com/auth/drive.readonly",
    "https://www.googleapis.com/auth/drive.file",
]

# Path to client secret JSON file for OAuth (downloaded from GCP Console).
# Resolution order: env var → project-root-relative → raises clear error.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLIENT_SECRETS_FILE = os.getenv(
    "GA4_CLIENT_SECRETS_PATH",
    str(_PROJECT_ROOT / "client_secrets.json"),
)

# OAuth state store
# Google OAuth redirects the browser away from Streamlit, which destroys the
# in-memory ``st.session_state``. The PKCE code_verifier (and redirect URI) are
# therefore persisted in a tiny JSON file keyed by the OAuth ``state`` value that
# Google returns in the callback URL. The store is pruned on every read/write.


def _state_store_dir() -> Path:
    dir_path = Path(os.getenv("GA4_OAUTH_STATE_DIR", tempfile.gettempdir())) / "ga4_insight_oauth"
    dir_path.mkdir(parents=True, exist_ok=True)
    return dir_path


def _safe_state_filename(state: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", state)


def _prune_state_store(max_age_seconds: float = 600) -> None:
    now = time.time()
    for file_path in _state_store_dir().iterdir():
        if file_path.is_file():
            try:
                if now - file_path.stat().st_mtime > max_age_seconds:
                    file_path.unlink()
            except OSError:
                pass


def save_oauth_state(state: str, code_verifier: str, redirect_uri: str) -> None:
    """Persist PKCE code_verifier and redirect_uri keyed by OAuth state.

    Args:
        state: The OAuth state returned by ``flow.authorization_url``.
        code_verifier: The PKCE code_verifier generated by the flow.
        redirect_uri: The redirect URI used to initiate the OAuth flow.
    """
    if not state or not code_verifier:
        return
    _prune_state_store()
    data = {
        "code_verifier": code_verifier,
        "redirect_uri": redirect_uri,
        "created_at": time.time(),
    }
    file_path = _state_store_dir() / f"{_safe_state_filename(state)}.json"
    file_path.write_text(json.dumps(data))
    if os.name != "nt":
        try:
            file_path.chmod(0o600)
        except OSError:
            pass  # Best-effort; some filesystems (network mounts, etc.) may not support chmod


def load_oauth_state(state: str) -> dict[str, Any] | None:
    """Load and remove the persisted OAuth state data.

    Args:
        state: The OAuth state from the callback URL.

    Returns:
        Dict with ``code_verifier`` and ``redirect_uri``, or ``None`` if the state
        is missing or expired.
    """
    if not state:
        return None
    _prune_state_store()
    file_path = _state_store_dir() / f"{_safe_state_filename(state)}.json"
    if not file_path.exists():
        return None
    try:
        data = json.loads(file_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    try:
        file_path.unlink()
    except OSError:
        pass
    return data


def get_auth_url(redirect_uri: str) -> tuple[str, Flow]:
    """Generate a Google OAuth authorization URL.

    Returns (url, flow). The flow is returned for compatibility, but the
    state data needed to complete the OAuth flow is persisted automatically so
    the callback can recreate the flow after the browser redirect.

    Raises:
        FileNotFoundError: If the client secrets file doesn't exist, with
            instructions for downloading it from the Google Cloud Console.
    """
    secrets_path = Path(CLIENT_SECRETS_FILE)
    if not secrets_path.exists():
        raise FileNotFoundError(
            f"\n\nGoogle OAuth client secrets file not found.\n"
            f"Expected at: {secrets_path.resolve()}\n\n"
            f"To fix this:\n"
            f"  1. Go to https://console.cloud.google.com/apis/credentials\n"
            f"  2. Click your OAuth 2.0 Client ID\n"
            f"  3. Click 'Download JSON'\n"
            f"  4. Save the file as 'client_secrets.json' in:\n"
            f"     {_PROJECT_ROOT.resolve()}/\n\n"
            f"   Or set the GA4_CLIENT_SECRETS_PATH env var to point\n"
            f"   to your file's actual location.\n"
        )

    flow = Flow.from_client_secrets_file(
        str(secrets_path),
        scopes=SCOPES,
        redirect_uri=redirect_uri,
    )
    auth_url, state = flow.authorization_url(
        access_type="offline",
        prompt="consent",  # Always get a refresh token
    )
    # Persist the PKCE code_verifier so the callback can recreate the flow.
    # ``st.session_state`` is destroyed when Google redirects the browser away,
    # so the verifier must live in a temporary file keyed by OAuth state.
    save_oauth_state(state, flow.code_verifier, redirect_uri)
    return auth_url, flow


def needs_scope_migration(credentials: Credentials) -> bool:
    """True if cached credentials are missing any currently required scope.

    Uses ``issubset()`` so that extra scopes (e.g. from a previous wider grant)
    don't trigger a false migration warning — only *missing* required scopes
    flag the credentials as stale.
    """
    granted = set(credentials.scopes or [])
    required = set(SCOPES)
    return not required.issubset(granted)


def _revoke_token(credentials: Credentials) -> None:
    """Revoke the entire OAuth grant at Google's revocation endpoint.

    Google's /revoke invalidates the entire grant regardless of which token
    you pass — only one call is needed. Prefers the refresh token (longer-lived)
    over the access token.

    Best-effort — failures are logged to stderr (visible in the developer's
    terminal but invisible to the user) and never block re-authentication.
    """
    logger = logging.getLogger(__name__)
    token = credentials.refresh_token or credentials.token
    if not token:
        return
    try:
        requests.post(
            "https://oauth2.googleapis.com/revoke",
            params={"token": token},
            headers={"content-type": "application/x-www-form-urlencoded"},
            timeout=5,
        )
    except requests.RequestException as e:
        logger.warning("Token revocation failed (non-critical): %s", e)


def exchange_code(
    code: str,
    redirect_uri: str,
    state: str | None = None,
) -> Credentials:
    """Exchange the OAuth authorization code for credentials.

    The ``Flow`` object is recreated from the persisted OAuth state because
    Streamlit's session state is lost during the Google redirect.

    Args:
        code: The authorization code from the callback URL.
        redirect_uri: The same redirect URI used to start the OAuth flow.
        state: The OAuth state from the callback URL (used to look up the
            PKCE code_verifier).

    Returns:
        A Google OAuth ``Credentials`` instance.

    Raises:
        ValueError: If the OAuth state is missing or expired.
    """
    if not state:
        raise ValueError(
            "OAuth callback is missing the 'state' parameter. " "Please sign in again."
        )

    stored = load_oauth_state(state)
    if not stored:
        raise ValueError("OAuth state not found or expired. Please sign in again.")

    flow = Flow.from_client_secrets_file(
        str(Path(CLIENT_SECRETS_FILE)),
        scopes=SCOPES,
        redirect_uri=redirect_uri,
        code_verifier=stored["code_verifier"],
    )
    flow.fetch_token(code=code)
    return flow.credentials


def credentials_to_dict(creds: Credentials) -> dict[str, Any]:
    """Serialize credentials to a JSON-safe dict for st.session_state."""
    return {
        "token": creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri": creds.token_uri,
        "client_id": creds.client_id,
        "client_secret": creds.client_secret,
        "scopes": creds.scopes,
    }


def credentials_from_dict(creds_dict: dict[str, Any]) -> Credentials:
    """Deserialize credentials from a JSON-safe dict."""
    return Credentials(**creds_dict)


def pull_ga4_report(
    credentials: Credentials,
    property_id: str,
    start_date: str = "90daysAgo",
    end_date: str = "today",
) -> pd.DataFrame:
    """Pull a standard GA4 report and return as a pandas DataFrame.

    Fetches: date, pagePath, deviceCategory dimensions
             + sessions, totalUsers, activeUsers, engagementRate, bounceRate metrics.
    """
    # Refresh token if needed
    if credentials.expired and credentials.refresh_token:
        credentials.refresh(Request())

    client = BetaAnalyticsDataClient(credentials=credentials)

    request = RunReportRequest(
        property=f"properties/{property_id}",
        dimensions=[
            Dimension(name="date"),
            Dimension(name="pagePath"),
            Dimension(name="deviceCategory"),
        ],
        metrics=[
            Metric(name="sessions"),
            Metric(name="totalUsers"),
            Metric(name="activeUsers"),
            Metric(name="engagementRate"),
            Metric(name="bounceRate"),
        ],
        date_ranges=[DateRange(start_date=start_date, end_date=end_date)],
        limit=100000,  # GA4 API max per request
    )

    response = client.run_report(request)

    # Build DataFrame from response rows
    rows = []
    for row in response.rows:
        rows.append(
            {
                "date": row.dimension_values[0].value,
                "page_path": row.dimension_values[1].value,
                "device_category": row.dimension_values[2].value,
                "sessions": int(row.metric_values[0].value),
                "users": int(row.metric_values[1].value),
                "active_users": int(row.metric_values[2].value),
                "engagement_rate": float(row.metric_values[3].value),
                "bounce_rate": float(row.metric_values[4].value),
            }
        )

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)
    df["date"] = pd.to_datetime(df["date"])
    return df
