"""Google Analytics 4 Data API client with OAuth 2.0 authentication."""

from __future__ import annotations

import json
import logging
import os
import re
import tempfile
import time
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from utils.data_context import GA4RequestMetadata

import pandas as pd
import requests
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
)
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow

# OAuth scopes — analytics.readonly for GA4 data pulls,
# drive.file for user-initiated exports only.
SCOPES = [
    "https://www.googleapis.com/auth/analytics.readonly",
    "https://www.googleapis.com/auth/drive.file",
]

# Path to client secret JSON file for OAuth (downloaded from GCP Console).
# Resolution order: env var → project-root-relative → raises clear error.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLIENT_SECRETS_FILE = os.getenv(
    "GA4_CLIENT_SECRETS_PATH",
    str(_PROJECT_ROOT / "client_secrets.json"),
)

# OAuth state store
# Google OAuth redirects the browser away from Streamlit, which destroys the
# in-memory ``st.session_state``. The PKCE code_verifier (and redirect URI) are
# therefore persisted in a tiny JSON file keyed by the OAuth ``state`` value that
# Google returns in the callback URL. The store is pruned on every read/write.


def _state_store_dir() -> Path:
    dir_path = Path(os.getenv("GA4_OAUTH_STATE_DIR", tempfile.gettempdir())) / "ga4_insight_oauth"
    dir_path.mkdir(parents=True, exist_ok=True, mode=0o700)
    if os.name != "nt":
        try:
            dir_path.chmod(0o700)
        except OSError:
            pass
    return dir_path


def _safe_state_filename(state: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", state)


def _prune_state_store(max_age_seconds: float = 600) -> None:
    """Remove expired state files. Enforces both age and a hard file-count cap."""
    logger = logging.getLogger(__name__)
    now = time.time()
    store_dir = _state_store_dir()
    state_files = sorted(
        [f for f in store_dir.iterdir() if f.is_file() and f.suffix == ".json"],
        key=lambda f: f.stat().st_mtime,
    )

    # Hard cap: keep at most 100 state files, remove oldest first
    MAX_STATE_FILES = 100
    while len(state_files) > MAX_STATE_FILES:
        oldest = state_files.pop(0)
        try:
            oldest.unlink()
        except OSError:
            pass

    for file_path in state_files:
        try:
            # Verify both filesystem age AND parsed created_at timestamp
            file_age = now - file_path.stat().st_mtime
            if file_age > max_age_seconds:
                file_path.unlink()
                continue
            # Double-check parsed timestamp for defense-in-depth
            try:
                data = json.loads(file_path.read_text())
                created = data.get("created_at", 0)
                if now - created > max_age_seconds:
                    file_path.unlink()
            except (json.JSONDecodeError, OSError):
                # Malformed file — remove it
                file_path.unlink()
                logger.debug("Removed malformed OAuth state file: %s", file_path.name)
        except OSError:
            pass


def save_oauth_state(state: str, code_verifier: str, redirect_uri: str) -> None:
    """Persist PKCE code_verifier and redirect_uri keyed by OAuth state.

    Args:
        state: The OAuth state returned by ``flow.authorization_url``.
        code_verifier: The PKCE code_verifier generated by the flow.
        redirect_uri: The redirect URI used to initiate the OAuth flow.
    """
    if not state or not code_verifier:
        return
    _prune_state_store()
    data = {
        "code_verifier": code_verifier,
        "redirect_uri": redirect_uri,
        "created_at": time.time(),
    }
    file_path = _state_store_dir() / f"{_safe_state_filename(state)}.json"
    # Atomic write: write to temp file, set permissions, then replace
    try:
        with NamedTemporaryFile(
            mode="w",
            dir=_state_store_dir(),
            prefix=".tmp_",
            suffix=".json",
            delete=False,
        ) as tmp:
            json.dump(data, tmp)
            tmp_path = Path(tmp.name)
        if os.name != "nt":
            try:
                tmp_path.chmod(0o600)
            except OSError:
                pass
        os.replace(tmp_path, file_path)
    except OSError:
        # Last-resort: fall back to direct write if atomic path fails
        file_path.write_text(json.dumps(data))
        if os.name != "nt":
            try:
                file_path.chmod(0o600)
            except OSError:
                pass


def load_oauth_state(state: str) -> dict[str, Any] | None:
    """Load and remove the persisted OAuth state data.

    Args:
        state: The OAuth state from the callback URL.

    Returns:
        Dict with ``code_verifier`` and ``redirect_uri``, or ``None`` if the state
        is missing or expired.
    """
    if not state:
        return None
    _prune_state_store()
    file_path = _state_store_dir() / f"{_safe_state_filename(state)}.json"
    if not file_path.exists():
        return None
    try:
        data = json.loads(file_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    try:
        file_path.unlink()
    except OSError:
        pass
    return data


def get_auth_url(redirect_uri: str) -> tuple[str, Flow]:
    """Generate a Google OAuth authorization URL.

    Returns (url, flow). The flow is returned for compatibility, but the
    state data needed to complete the OAuth flow is persisted automatically so
    the callback can recreate the flow after the browser redirect.

    Raises:
        FileNotFoundError: If the client secrets file doesn't exist, with
            instructions for downloading it from the Google Cloud Console.
    """
    secrets_path = Path(CLIENT_SECRETS_FILE)
    if not secrets_path.exists():
        raise FileNotFoundError(
            f"\n\nGoogle OAuth client secrets file not found.\n"
            f"Expected at: {secrets_path.resolve()}\n\n"
            f"To fix this:\n"
            f"  1. Go to https://console.cloud.google.com/apis/credentials\n"
            f"  2. Click your OAuth 2.0 Client ID\n"
            f"  3. Click 'Download JSON'\n"
            f"  4. Save the file as 'client_secrets.json' in:\n"
            f"     {_PROJECT_ROOT.resolve()}/\n\n"
            f"   Or set the GA4_CLIENT_SECRETS_PATH env var to point\n"
            f"   to your file's actual location.\n"
        )

    flow = Flow.from_client_secrets_file(
        str(secrets_path),
        scopes=SCOPES,
        redirect_uri=redirect_uri,
    )
    auth_url, state = flow.authorization_url(
        access_type="offline",
        prompt="consent",  # Always get a refresh token
    )
    # Persist the PKCE code_verifier so the callback can recreate the flow.
    # ``st.session_state`` is destroyed when Google redirects the browser away,
    # so the verifier must live in a temporary file keyed by OAuth state.
    save_oauth_state(state, flow.code_verifier, redirect_uri)
    return auth_url, flow


def needs_scope_migration(credentials: Credentials) -> bool:
    """True if cached credentials are missing any currently required scope.

    Uses ``issubset()`` so that extra scopes (e.g. from a previous wider grant)
    don't trigger a false migration warning — only *missing* required scopes
    flag the credentials as stale.
    """
    granted = set(credentials.scopes or [])
    required = set(SCOPES)
    return not required.issubset(granted)


def _revoke_token(credentials: Credentials) -> None:
    """Revoke the entire OAuth grant at Google's revocation endpoint.

    Google's /revoke invalidates the entire grant regardless of which token
    you pass — only one call is needed. Prefers the refresh token (longer-lived)
    over the access token.

    Best-effort — failures are logged and never block re-authentication.
    """
    logger = logging.getLogger(__name__)
    token = credentials.refresh_token or credentials.token
    if not token:
        return
    try:
        response = requests.post(
            "https://oauth2.googleapis.com/revoke",
            data={"token": token},
            headers={"content-type": "application/x-www-form-urlencoded"},
            timeout=5,
        )
        if not response.ok:
            logger.warning("OAuth revocation returned HTTP %s", response.status_code)
    except requests.RequestException as e:
        logger.warning("Token revocation failed (non-critical): %s", e)


def exchange_code(
    code: str,
    redirect_uri: str,
    state: str | None = None,
) -> Credentials:
    """Exchange the OAuth authorization code for credentials.

    The ``Flow`` object is recreated from the persisted OAuth state because
    Streamlit's session state is lost during the Google redirect.

    Args:
        code: The authorization code from the callback URL.
        redirect_uri: The same redirect URI used to start the OAuth flow.
        state: The OAuth state from the callback URL (used to look up the
            PKCE code_verifier).

    Returns:
        A Google OAuth ``Credentials`` instance.

    Raises:
        ValueError: If the OAuth state is missing, expired, or the
            redirect URI doesn't match the stored value.
    """
    if not state:
        raise ValueError(
            "OAuth callback is missing the 'state' parameter. " "Please sign in again."
        )

    stored = load_oauth_state(state)
    if not stored:
        raise ValueError("OAuth state not found or expired. Please sign in again.")

    # Validate redirect URI matches stored value (bind callback to original URI)
    if "redirect_uri" in stored and redirect_uri != stored["redirect_uri"]:
        raise ValueError("OAuth callback configuration changed. Please sign in again.")

    # Use stored redirect_uri for flow reconstruction
    flow_redirect_uri = stored.get("redirect_uri", redirect_uri)

    flow = Flow.from_client_secrets_file(
        str(Path(CLIENT_SECRETS_FILE)),
        scopes=SCOPES,
        redirect_uri=flow_redirect_uri,
        code_verifier=stored["code_verifier"],
    )
    flow.fetch_token(code=code)
    return flow.credentials


def credentials_to_dict(creds: Credentials) -> dict[str, Any]:
    """Serialize credentials to a JSON-safe dict for st.session_state."""
    return {
        "token": creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri": creds.token_uri,
        "client_id": creds.client_id,
        "client_secret": creds.client_secret,
        "scopes": creds.scopes,
    }


def credentials_from_dict(creds_dict: dict[str, Any]) -> Credentials:
    """Deserialize credentials from a JSON-safe dict."""
    return Credentials(**creds_dict)


def pull_ga4_report(
    credentials: Credentials,
    property_id: str,
    start_date: str = "90daysAgo",
    end_date: str = "today",
) -> tuple[pd.DataFrame, GA4RequestMetadata]:
    """Pull a standard GA4 report with pagination and return (DataFrame, metadata).

    v0.2.0: Now returns a GA4RequestMetadata alongside the DataFrame so the
    DataContext factory can produce a canonical source fingerprint without
    UI reconstruction drift.

    Fetches: date, pagePath, deviceCategory dimensions
             + sessions, totalUsers, activeUsers, engagementRate, bounceRate metrics.

    Pages through results using offset + limit. Stops on empty page,
    reported total, or hard cap (500k rows). Deduplicates on the expected
    dimension tuple (date, page_path, device_category).
    """
    from utils.data_context import GA4RequestMetadata

    DIMENSIONS = ["date", "pagePath", "deviceCategory"]
    METRICS = ["sessions", "totalUsers", "activeUsers", "engagementRate", "bounceRate"]
    HARD_CAP = 500_000
    PAGE_SIZE = 100_000  # GA4 API max per request

    # Refresh token if needed
    if credentials.expired and credentials.refresh_token:
        credentials.refresh(Request())

    client = BetaAnalyticsDataClient(credentials=credentials)

    all_rows = []
    seen = set()
    offset = 0

    while offset < HARD_CAP:
        request = RunReportRequest(
            property=f"properties/{property_id}",
            dimensions=[
                Dimension(name="date"),
                Dimension(name="pagePath"),
                Dimension(name="deviceCategory"),
            ],
            metrics=[
                Metric(name="sessions"),
                Metric(name="totalUsers"),
                Metric(name="activeUsers"),
                Metric(name="engagementRate"),
                Metric(name="bounceRate"),
            ],
            date_ranges=[DateRange(start_date=start_date, end_date=end_date)],
            limit=PAGE_SIZE,
            offset=offset,
        )

        response = client.run_report(request)

        if not response.rows:
            break  # No more data

        for row in response.rows:
            key = (
                row.dimension_values[0].value,
                row.dimension_values[1].value,
                row.dimension_values[2].value,
            )
            if key not in seen:
                seen.add(key)
                all_rows.append(
                    {
                        "date": row.dimension_values[0].value,
                        "page_path": row.dimension_values[1].value,
                        "device_category": row.dimension_values[2].value,
                        "sessions": int(row.metric_values[0].value),
                        "users": int(row.metric_values[1].value),
                        "active_users": int(row.metric_values[2].value),
                        "engagement_rate": float(row.metric_values[3].value),
                        "bounce_rate": float(row.metric_values[4].value),
                    }
                )

        offset += PAGE_SIZE

        # Check if we've reached the reported total
        if response.row_count and offset >= response.row_count:
            break

    truncated = len(all_rows) >= HARD_CAP

    metadata = GA4RequestMetadata(
        property_id=property_id,
        date_range=(start_date, end_date),
        dimensions=DIMENSIONS,
        metrics=METRICS,
        limit=HARD_CAP,
        truncated=truncated,
    )

    if not all_rows:
        return pd.DataFrame(), metadata

    df = pd.DataFrame(all_rows)
    df["date"] = pd.to_datetime(df["date"])
    return df, metadata
