"""Report exporter — builds downloadable Markdown reports from chat sessions."""

import base64
from typing import Any
import pandas as pd
import plotly.graph_objects as go


def build_markdown_report(
    summary: str | None,
    chat_history: list[dict[str, Any]],
    stats: dict[str, Any],
    data_source: str | None = None,
) -> str:
    """Build a Markdown report from the current session.

    Includes dataset overview, AI summary (if available), and Q&A with
    embedded chart PNGs (if kaleido is installed).
    """
    lines: list[str] = []

    lines.append("# 📊 GA4 Insight Explorer — Report")
    lines.append("")
    lines.append(f"*Generated on {pd.Timestamp.now().strftime('%Y-%m-%d at %H:%M')}*")
    lines.append(f"*Data source: {data_source or 'Unknown'}*")
    lines.append("")

    lines.append("## 📋 Dataset Overview")
    lines.append("")
    lines.append(f"- **Rows:** {stats.get('row_count', 'N/A'):,}")
    lines.append(f"- **Columns:** {stats.get('column_count', 'N/A')}")
    lines.append(
        f"- **Date range:** {stats.get('date_range_start', 'N/A')} "
        f"→ {stats.get('date_range_end', 'N/A')}"
    )
    lines.append("")

    if summary:
        lines.append("## 🤖 AI-Generated Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    if chat_history:
        lines.append("## 💬 Q&A")
        lines.append("")
        for i, entry in enumerate(chat_history, 1):
            if entry.get("response") and entry["response"] != "":
                lines.append(f"### Q{i}: {entry['question']}")
                lines.append("")
                lines.append(entry["response"])
                lines.append("")
                if entry.get("chart") and entry["chart"].get("fig"):
                    chart_png = _chart_to_base64(entry["chart"]["fig"])
                    if chart_png:
                        lines.append(f"![Chart for Q{i}]({chart_png})")
                        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*Report generated by [GA4 Insight Explorer]"
        "(https://github.com/griffinkelton/insights-explorer)*"
    )

    return "\n".join(lines)


def _chart_to_base64(fig: go.Figure) -> str | None:
    """Convert Plotly figure to base64 PNG. Requires kaleido.

    Returns None if kaleido is not installed or conversion fails.
    """
    try:
        img_bytes = fig.to_image(format="png", scale=2)
        b64 = base64.b64encode(img_bytes).decode("utf-8")
        return f"data:image/png;base64,{b64}"
    except Exception:
        return None  # Silently skip if kaleido isn't installed
