/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDriveCallbackRouteImport } from './routes/auth/drive/callback'
import { Route as AuthGa4CallbackRouteImport } from './routes/auth/ga4/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriveCallbackRoute = AuthDriveCallbackRouteImport.update({
  id: '/auth/drive/callback',
  path: '/auth/drive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGa4CallbackRoute = AuthGa4CallbackRouteImport.update({
  id: '/auth/ga4/callback',
  path: '/auth/ga4/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/ga4/callback': typeof AuthGa4CallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/ga4/callback': typeof AuthGa4CallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/ga4/callback': typeof AuthGa4CallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/drive/callback' | '/auth/ga4/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/drive/callback' | '/auth/ga4/callback'
  id: '__root__' | '/' | '/auth/drive/callback' | '/auth/ga4/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthDriveCallbackRoute: typeof AuthDriveCallbackRoute
  AuthGa4CallbackRoute: typeof AuthGa4CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/drive/callback': {
      id: '/auth/drive/callback'
      path: '/auth/drive/callback'
      fullPath: '/auth/drive/callback'
      preLoaderRoute: typeof AuthDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ga4/callback': {
      id: '/auth/ga4/callback'
      path: '/auth/ga4/callback'
      fullPath: '/auth/ga4/callback'
      preLoaderRoute: typeof AuthGa4CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthDriveCallbackRoute: AuthDriveCallbackRoute,
  AuthGa4CallbackRoute: AuthGa4CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
